# Usa la imagen oficial de MongoDB como base
FROM mongo:latest

# Establece una variable de entorno (si es necesario)
# ENV MONGO_INITDB_ROOT_USERNAME=admin
# ENV MONGO_INITDB_ROOT_PASSWORD=password

# (Opcional) Copia archivos de configuración personalizados, si los tienes
# COPY mongodb.conf /etc/mongod.conf

# (Opcional) Expone el puerto en el que MongoDB escucha (por defecto, 27017)
# EXPOSE 27017

# (Opcional) Puedes agregar otros comandos o configuraciones personalizadas aquí

# Comando para iniciar MongoDB
CMD ["mongod"]
