[build]
  command = "docker build -t tu_imagen_docker:etiqueta ."
  functions = "./flask/ventanas/netlify/functions"

[context.production]
  command = "docker run -p 8080:8080 tu_imagen_docker:etiqueta"
